/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:556fc859-5440-4457-8ce3-f55bf080db1b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CbsrV3dVF",
    "aws_user_pools_web_client_id": "1g2qape4io7av5t4l7iss241j1",
    "oauth": {
        "domain": "primemaster5b5aed3b-5b5aed3b-envn.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://gruf4ziul5gafizv3v4rdeahgq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
